# Generated by Django 3.0.5 on 2021-11-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishname', models.CharField(max_length=300)),
                ('hindiname', models.CharField(max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/products/')),
                ('categoryid', models.PositiveIntegerField(null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
    ]
