# Generated by Django 3.0.5 on 2021-11-28 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0004_product_categoryname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoryname',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bazaar.Category'),
        ),
    ]
