# Generated by Django 3.0.5 on 2021-12-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0009_auto_20211128_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customername',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
